services:
  db:
    image: mongo:8.0
    container_name: pokedex-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongovol:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: pokedex-mongo-express
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://db:27017/
      ME_CONFIG_BASICAUTH: false

  api:
    image: node:25-alpine
    container_name: pokedex-backend
    depends_on:
      - db
    working_dir: /app
    environment:
      DATABASE_URL: mongodb://db:27017/pokedex
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  frontend:
    image: node:25-alpine
    container_name: pokedex-frontend
    depends_on:
      - api
    working_dir: /app
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

volumes:
  mongovol: